sudo: false
language: ruby
cache: bundler
addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
services:
  - elasticsearch
rvm:
  - "2.3.0"
before_install:
  - gem update --system
  - gem --version
  - gem update bundler
script:
  - RAILS_ENV=test bundle exec rake db:reset
  - RELOAD_INDICES=true bundle exec rake test
  - bundle exec rake spec
